services:
  - type: web
    name: dog-api-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: NODE_ENV
        value: production
